### ISSUE TITLE
Couldn't find ngCookies

### ISSUE THREAD

**Issue by ln206** [auth0/angular-storage#53]
Hi, I'm having this error

`Error: [$injector:nomod] Module 'ngCookies' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

I even tried to install `ngCookies`. but it still didn't work. Anyone else having this problem?

**Comment by 4kochi** [comment]
The new version of angular-storage (0.0.14) uses ngCookies instead of the deprecated ngCookieStore. Besides installing ngCookies do you have injected the ngCookies service in your app?

```
angular.module('myApp', ['ngCookies', 'angular-storage'])
```

**Comment by ln206** [comment]
@4kochi yes, I also did that. It didn't work.

**Comment by 4kochi** [comment]
Maybe you should try a minimal working example like the following to narrow down the problem. And then include angular-storage as next step.

```
angular.module('cookiesExample', ['ngCookies'])
.controller('ExampleController', ['$cookies', function($cookies) {
  // Retrieving a cookie
  var favoriteCookie = $cookies.get('myFavorite');
  // Setting a cookie
  $cookies.put('myFavorite', 'oatmeal');
}]);
```

**Comment by ln206** [comment]
Thanks for the responses, @4kochi. But i ended up using another angular plugin for local storage.

**Comment by rictorres** [comment]
I got the same here. For now I'm sticking with v0.0.11

**Comment by jsancho** [comment]
This broke my CI build
Specifying version 0.0.12 in my bower.json resolved it.

**Comment by jxkolesnikov** [comment]
Why do I need inject additional dependecies to my module? Why didn't you inject ngCookies to your module angular-storage?

**Comment by westy92** [comment]
I agree with @jxkolesnikov.  If it's a dependency, why isn't it injected at a module level and listed as a dependency in the package.json/bower.json?

**Comment by rodneyjoyce** [comment]
Note: I had the same problem and installing ngCookies fixed it. I was testing storing stuff in localstorage in Chrome incognito mode and it was failing until I did that...  would be good if the could be handled in the packaging.

**Comment by rictorres** [comment]
[Earlier last year](https://github.com/auth0/angular-storage/issues/53#issuecomment-202184278) I decided to stick with `v0.0.11`, which seemed fine at the time but led to errors in the past months.

My apps were broken on Safari incognito mode because the `cookie` fallback was failing. I'm gonna send a PR soon, but in the mean time you can:

- install `angular-cookies`
- inject it into your module `angular.module('myApp', ['ngCookies', 'angular-storage'])`
- use `v0.0.14` of this library (**important**)

`v0.0.14` is the only _new_ version which imports and uses `ngCookies` correctly.

**Comment by rictorres** [comment]
PR sent: https://github.com/auth0/angular-storage/pull/59
